version: 2

sources:
  - name: wapolice
    description: Suburb crime statistics downloaded from the WA Police website
    database: sbx_raw
    schema: wapolice
    tables:
      - name: raw_wapolice
        description: Suburb crime statistics downloaded from the WA Police website
        columns:
          - name: file_name
            description: Name of Suburb
            tests:
              - unique
              - not_null           